spring:
  profiles:
    include: application-local.yml
    active: default
  datasource:
    url: jdbc:h2:file:~/tasks
    username: sa
    password: null
    driver-class-name: org.h2.Driver
  jpa:
    database: postgresql
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
  jackson:
    mapper:
      DEFAULT_VIEW_INCLUSION: true
security:
  oauth2:
    resource:
      user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
      prefer-token-info: false
logging:
  level:
    org:
      springframework: info